### ISSUE TITLE
[#01] 프론트 분석 및 AWS 구축

### ISSUE THREAD

**Issue by min3009** [WeDontKnowAnything/jobadream_frontend#1]
### Task List 

- [x] 기존 코드 구조 파악
- [x] 사용된 라이브러리 목록 정리
- [x] AWS clould front 구축
### 버그 리포트

1.
