### ISSUE TITLE
[#02] Template PoC

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_frontend#2]
### Task List 

- [ ] HTTP 통신
- [ ] REST API
- [ ] Axios
- [ ] vue.js 기초 학습
- [ ] 상태관리 개념 학습
  - [ ] Pinia - vue 
- [ ] Vuetify 및 Vuexy 템플릿 구조 학습

### 버그 리포트

1.

**Comment by yongjoo0329** [comment]
화이팅!
