### ISSUE TITLE
[#04] 상세 화면 개발

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_frontend#4]
### Task List 

- [x] 관련 사이트 참고
- [ ] 기업 정보 상세 화면 
    - [ ] 설계
    - [ ] 개발
- [ ] 채용 정보 상세 화면 
    - [ ] 설계
    - [ ] 개발
 
### 버그 리포트

1.

**Comment by yongjoo0329** [comment]
ApexChart 사용하기
https://apexcharts.com/docs/vue-charts/
